# Generated by Django 2.2.2 on 2019-12-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='ia_active',
            field=models.BooleanField(default=True, verbose_name='активная'),
        ),
    ]
