# Generated by Django 2.2.2 on 2019-12-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_productcategory_ia_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='ia_active',
            new_name='is_active',
        ),
    ]
